// ui-angular/src/app/components/add-item-form/add-item-form.component.ts
import { Component, output, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-add-item-form',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './add-item-form.component.html'
})
export class AddItemFormComponent {
  // Plain properties for two-way ngModel binding
  title = '';
  description = '';

  loading = signal(false);
  error = signal<string | null>(null);

  add = output<{ title: string; description?: string }>();

  handleSubmit(): void {
    const trimmedTitle = this.title.trim();
    if (!trimmedTitle) return;

    this.loading.set(true);
    this.error.set(null);

    this.add.emit({
      title: trimmedTitle,
      description: this.description.trim() || undefined
    });

    this.title = '';
    this.description = '';
    this.loading.set(false);
  }
}

<form (ngSubmit)="handleSubmit()" class="bg-white border border-gray-200 rounded-xl p-5 shadow-sm space-y-3">
  <h2 class="text-base font-semibold text-gray-700">Add item</h2>

  @if (error()) {
    <p class="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">{{ error() }}</p>
  }

  <input
    type="text"
    placeholder="Title *"
    [(ngModel)]="title"
    name="title"
    maxlength="255"
    required
    class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
  />

  <input
    type="text"
    placeholder="Description (optional)"
    [(ngModel)]="description"
    name="description"
    maxlength="4000"
    class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
  />

  <button
    type="submit"
    [disabled]="!title.trim()"
    class="w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
  >
    Add item
  </button>
</form>

// ui-react/src/components/AddItemForm.tsx
import { useState, type FormEvent } from 'react';

interface Props {
  onAdd: (title: string, description?: string) => Promise<void>;
}

export default function AddItemForm({ onAdd }: Props) {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setLoading(true);
    setError(null);
    try {
      await onAdd(title.trim(), description.trim() || undefined);
      setTitle('');
      setDescription('');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add item');
    } finally {
      setLoading(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm space-y-3">
      <h2 className="text-base font-semibold text-gray-700">Add item</h2>

      {error && (
        <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">{error}</p>
      )}

      <input
        type="text"
        placeholder="Title *"
        value={title}
        onChange={e => setTitle(e.target.value)}
        maxLength={255}
        required
        className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
      />

      <input
        type="text"
        placeholder="Description (optional)"
        value={description}
        onChange={e => setDescription(e.target.value)}
        maxLength={4000}
        className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
      />

      <button
        type="submit"
        disabled={loading || !title.trim()}
        className="w-full rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {loading ? 'Adding…' : 'Add item'}
      </button>
    </form>
  );
}
