// ui-angular/src/app/components/item-list/item-list.component.ts
import { Component, input, output } from '@angular/core';
import { ChecklistItem } from '../../checklist/checklist-item.model';
import { ItemRowComponent } from '../item-row/item-row.component';

@Component({
  selector: 'app-item-list',
  standalone: true,
  imports: [ItemRowComponent],
  templateUrl: './item-list.component.html'
})
export class ItemListComponent {
  items = input.required<ChecklistItem[]>();
  delete = output<number>();
}

<ul class="space-y-2">
  @for (item of items(); track item.id) {
    <app-item-row [item]="item" (delete)="delete.emit($event)" />
  } @empty {
    <p class="text-center text-sm text-gray-400 py-10">No items yet. Add one above.</p>
  }
</ul>

// ui-react/src/components/ItemList.tsx
import type { ChecklistItem } from '../types/ChecklistItem';
import ItemRow from './ItemRow';

interface Props {
  items: ChecklistItem[];
  onDelete: (id: number) => Promise<void>;
}

export default function ItemList({ items, onDelete }: Props) {
  if (items.length === 0) {
    return (
      <p className="text-center text-sm text-gray-400 py-10">
        No items yet. Add one above.
      </p>
    );
  }

  return (
    <ul className="space-y-2">
      {items.map(item => (
        <ItemRow key={item.id} item={item} onDelete={onDelete} />
      ))}
    </ul>
  );
}
